version: '3.9'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: data_uptaeb
      MYSQL_USER: root_user
      MYSQL_PASSWORD: 123123
      MYSQL_ROOT_PASSWORD: 123123
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./bd.sql2.sql:/docker-entrypoint-initdb.d/bd.sql2.sql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
