version: '3.9'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tjmdb
      POSTGRES_USER: jaime
      POSTGRES_PASSWORD: 123123
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
