services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tjmdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123123
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
